### PR TITLE
fix empty biz body unwrapBinary EOF error

### LINKED ISSUE #69: UnwrapBinaryMessage return EOF error when biz resp is nil
**Describe the bug**

thrift.UnwrapBinaryMessage could not unwrap empty biz buf

**To Reproduce**

```
func TestBinaryUnwrap(t *testing.T) {
	b := BinaryProtocol{
		Buf:  nil,
		Read: 0,
	}
	var i32 int32 = -2147418110
	b.WriteI32(i32)
	b.WriteString("DummyNew")
	b.WriteI32(1)
	b.WriteByte(byte(STOP))
	_, _, _, _, _, err := UnwrapBinaryMessage(b.Buf)

	t.Errorf("UnwrapBinaryMessage() error = %v", err)

}
```

run the test case

**Expected behavior**

err is nil and body is empty slice bytes

**Screenshots**

**Version:**

v0.3.0

**Environment:**

**Additional context**

### PR DESCRIPTION
**Pull request by wodeqiangne**
#### What type of PR is this?
fix: A bug fix, UnwrapBinaryMessage return an EOF error when the biz body is empty

#### (Optional) Translate the PR title into Chinese.
修复空业务body在unwrapBinaryMessage遇到的EOF错误

#### (Optional) Which issue(s) this PR fixes:
Fixes #69

### CODE REVIEW

File: thrift/binary.go [hunk 1]
```diff
@@ -204,10 +204,14 @@ func (p BinaryProtocol) UnwrapBody() (string, TMessageType, int32, FieldID, []by
 		return name, rTyp, seqID, 0, nil, err
 	}
 	// read the success struct
-	_, _, structID, err := p.ReadFieldBegin()
+	_, typeId, structID, err := p.ReadFieldBegin()
 	if err != nil {
 		return name, rTyp, seqID, structID, nil, err
 	}
+	//empty response
+	if typeId == STOP {
```
Comment (AsterDY) [inline thrift/binary.go:212]: what's the reason to have nil body in READ WORLD?

Comment (wodeqiangne) [reply thrift/binary.go:212]: > what's the reason to have nil body in READ WORLD?

Unintentionally returned a nil resp

Comment (wodeqiangne) [reply thrift/binary.go:212]: > what's the reason to have nil body in READ WORLD?

btw it seems returning a nil body will not trigger error in other kitex thrift rpc call

**Review by AsterDY — APPROVED** [review]
